name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Initialize Windows Project
        run: |
          flutter config --enable-windows-desktop
          flutter create --platforms=windows .
          flutter pub get

      - name: Build App
        run: flutter build windows --release

      - name: Zip Release
        shell: powershell
        run: Compress-Archive -Path build\windows\runner\Release\* -DestinationPath team-system-windows.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          files: team-system-windows.zip
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
