name: Build Windows EXE

on:
  workflow_dispatch: # Nur manueller Start f√ºr maximale Kontrolle

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Nutzt immer die aktuellste stabile Version

      - name: Install Dependencies
        run: |
          flutter config --enable-windows-desktop
          flutter pub get

      - name: Build App
        run: flutter build windows --release

      - name: Zip and Release
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          files: build/windows/runner/Release/*
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
